package vn.bookshare.common.enums;

public enum ResponseCode {
    VALIDATION_ERROR,
    PASSWORD_NOT_MATCH_ERROR,
    USER_ALREADY_EXISTS_ERROR,
    EXPIRED_JWT_ERROR,
    JWT_INCORRECT_FORMAT,
    JWT_ERROR,
    JWT_UNSUPPORT_ERROR,
    USER_AUTHENTICATION_ERROR,
    INTERNAL_SERVER_ERROR,
    REGISTRATION_SUCCESSFUL,
    LOGIN_SUCCESSFUL,
    BAD_CREDENTIALS
}
